spring.config.import=optional:file:.env[.properties]

spring.application.name=${APP_NAME:api}

management.opentelemetry.tracing.export.otlp.endpoint=${OTLP_TRACING_ENDPOINT:}
management.opentelemetry.logging.export.otlp.endpoint=${OTLP_LOGGING_ENDPOINT:}
management.otlp.metrics.export.url=${OTLP_METRICS_ENDPOINT:}

management.tracing.sampling.probability=${TRACING_SAMPLING_RATE:0.1}
logging.level.web=${LOGGING_LEVEL_WEB:INFO}

app.security.headerName=${APP_SECURITY_HEADER_NAME:}
app.security.apiKey=${APP_SECURITY_API_KEY:}
