spring.application.name=api

management.opentelemetry.tracing.export.otlp.endpoint=http://127.0.0.1:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://127.0.0.1:4318/v1/logs
management.otlp.metrics.export.url=http://127.0.0.1:4318/v1/metrics

management.tracing.sampling.probability=1.0
logging.level.web=TRACE
